name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature", "Triage"]
projects: ["RSoulatIOHK/6"]
assignees:
  - RSoulatIOHK
  - bogdan-manole
  - KJES4
  - amnambiar
  - jankajg-iohk
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see added to the project.
      placeholder: ex. "I would like to see..."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Issue related
      description: Is your feature request related to a problem? If so, please describe."
      placeholder: ex. "I'm always frustrated when..."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: ex. "I would like to see..."
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered.
      placeholder: ex. "I could also..."
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the feature request here.
      placeholder: ex. "Add any other context or screenshots about the feature request here."
    validations:
      required: false